#include "glfw/glfw3.h"

#define X_KEY_SPACE                 GLFW_KEY_SPACE              
#define X_KEY_APOSTROPHE            GLFW_KEY_APOSTROPHE         
#define X_KEY_COMMA                 GLFW_KEY_COMMA              
#define X_KEY_MINUS                 GLFW_KEY_MINUS              
#define X_KEY_PERIOD                GLFW_KEY_PERIOD             
#define X_KEY_SLASH                 GLFW_KEY_SLASH              
#define X_KEY_0                     GLFW_KEY_0                  
#define X_KEY_1                     GLFW_KEY_1                  
#define X_KEY_2                     GLFW_KEY_2                  
#define X_KEY_3                     GLFW_KEY_3                  
#define X_KEY_4                     GLFW_KEY_4                  
#define X_KEY_5                     GLFW_KEY_5                  
#define X_KEY_6                     GLFW_KEY_6                  
#define X_KEY_7                     GLFW_KEY_7                  
#define X_KEY_8                     GLFW_KEY_8                  
#define X_KEY_9                     GLFW_KEY_9                  
#define X_KEY_SEMICOLON             GLFW_KEY_SEMICOLON          
#define X_KEY_EQUAL                 GLFW_KEY_EQUAL              
#define X_KEY_A                     GLFW_KEY_A                  
#define X_KEY_B                     GLFW_KEY_B                  
#define X_KEY_C                     GLFW_KEY_C                  
#define X_KEY_D                     GLFW_KEY_D                  
#define X_KEY_E                     GLFW_KEY_E                  
#define X_KEY_F                     GLFW_KEY_F                  
#define X_KEY_G                     GLFW_KEY_G                  
#define X_KEY_H                     GLFW_KEY_H                  
#define X_KEY_I                     GLFW_KEY_I                  
#define X_KEY_J                     GLFW_KEY_J                  
#define X_KEY_K                     GLFW_KEY_K                  
#define X_KEY_L                     GLFW_KEY_L                  
#define X_KEY_M                     GLFW_KEY_M                  
#define X_KEY_N                     GLFW_KEY_N                  
#define X_KEY_O                     GLFW_KEY_O                  
#define X_KEY_P                     GLFW_KEY_P                  
#define X_KEY_Q                     GLFW_KEY_Q                  
#define X_KEY_R                     GLFW_KEY_R                  
#define X_KEY_S                     GLFW_KEY_S                  
#define X_KEY_T                     GLFW_KEY_T                  
#define X_KEY_U                     GLFW_KEY_U                  
#define X_KEY_V                     GLFW_KEY_V                  
#define X_KEY_W                     GLFW_KEY_W                  
#define X_KEY_X                     GLFW_KEY_X                  
#define X_KEY_U                     GLFW_KEY_Y                  
#define X_KEY_Z                     GLFW_KEY_Z                  
#define X_KEY_LEFT_BRACKET          GLFW_KEY_LEFT_BRACKET       
#define X_KEY_BACKSLAH              GLFW_KEY_BACKSLASH          
#define X_KEY_RIGHT_BRACKET         GLFW_KEY_RIGHT_BRACKET      
#define X_KEY_GRAVE_ACCENT          GLFW_KEY_GRAVE_ACCENT       
#define X_KEY_WORLD_1               GLFW_KEY_WORLD_1            
#define X_KEY_WORLD_2               GLFW_KEY_WORLD_2            